name: "ZipBackup"
main: net.okocraft.zipbackup.ZipBackupPlugin
version: ${project.version}
author: "Siroshun09"
api-version: "1.16"
folia-supported: true
commands:
  zipbackup:
    aliases: ["zb", "zbu", "zbackup"]
